import ICAL from 'ical.js';
import type { AgendaEvent } from './garden-model.ts';
import { addDays,today } from './garden-model.ts';
const pr=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Puerto_Rico',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
function local(time:ICAL.Time){if(time.isDate||time.zone===ICAL.Timezone.localTimezone)return {date:`${time.year}-${String(time.month).padStart(2,'0')}-${String(time.day).padStart(2,'0')}`,time:time.isDate?'':`${String(time.hour).padStart(2,'0')}:${String(time.minute).padStart(2,'0')}`};const p=pr.formatToParts(time.toJSDate()),get=(t:string)=>p.find(x=>x.type===t)!.value;return {date:`${get('year')}-${get('month')}-${get('day')}`,time:`${get('hour')}:${get('minute')}`}}
export function parseCalendar(text:string,owner:string,source:string,from=addDays(today(),-30),until=addDays(today(),400)){if(text.length>2000000)throw Error('El archivo es demasiado grande. Exporta un solo calendario.');if(!text.includes('BEGIN:VCALENDAR'))throw Error('Escoge un archivo .ics; extrae primero el ZIP de Google.');const root=new ICAL.Component(ICAL.parse(text));for(const tz of root.getAllSubcomponents('vtimezone'))ICAL.TimezoneService.register(new ICAL.Timezone({component:tz}));const components=root.getAllSubcomponents('vevent'),masters=components.filter(c=>!c.hasProperty('recurrence-id')),out:AgendaEvent[]=[];const events=masters.map(c=>new ICAL.Event(c));for(const c of components.filter(c=>c.hasProperty('recurrence-id'))){const exception=new ICAL.Event(c),master=events.find(e=>e.uid===exception.uid);if(master)master.relateException(exception)}let iterations=0;for(const event of events){const push=(start:ICAL.Time,end:ICAL.Time,item:ICAL.Event,occurrence:string)=>{if(String(item.component.getFirstPropertyValue('status')).toUpperCase()==='CANCELLED')return;const a=local(start),b=local(end);if(a.date<from||a.date>until)return;out.push({id:crypto.randomUUID(),title:(item.summary||'Evento').slice(0,160),owner,date:a.date,time:a.time,endTime:a.date===b.date?b.time:'',category:'Agenda',notes:[item.description,item.location].filter(Boolean).join('\n').slice(0,3000),done:false,source,sourceUid:(event.uid+'|'+occurrence).slice(0,500)});if(out.length>3000)throw Error('Más de 3000 eventos. Exporta un calendario más pequeño.');};if(event.isRecurring()){const rules=event.component.getAllProperties('rrule');if(rules.some(r=>['SECONDLY','MINUTELY','HOURLY'].includes((r.getFirstValue() as ICAL.Recur).freq)))throw Error('Hay una repetición demasiado frecuente para importar.');const iterator=event.iterator();let occurrence:ICAL.Time|null;while((occurrence=iterator.next())){if(++iterations>30000)throw Error('El calendario tiene demasiadas repeticiones. Exporta un periodo más corto.');if(local(occurrence).date>until)break;const details=event.getOccurrenceDetails(occurrence);push(details.startDate,details.endDate,details.item,occurrence.toString())}}else push(event.startDate,event.endDate,event,event.startDate.toString())}return out}
export function mergeCalendar(existing:AgendaEvent[],incoming:AgendaEvent[]){const next=[...existing];for(const e of incoming){const index=next.findIndex(x=>x.owner===e.owner&&x.source===e.source&&x.sourceUid===e.sourceUid);if(index<0)next.push(e);else next[index]={...e,id:next[index].id,done:next[index].done}}return next}
const escape=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
function fold(line:string){const enc=new TextEncoder();let current='',parts:string[]=[];for(const char of line){if(enc.encode(current+char).length>73){parts.push(current);current=' '+char}else current+=char}parts.push(current);return parts.join('\r\n')}
export function exportCalendar(events:AgendaEvent[]){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Jardin de dos//Agenda//ES','CALSCALE:GREGORIAN'];for(const e of events){const date=e.date.replace(/-/g,''),time=e.time.replace(':','');lines.push('BEGIN:VEVENT','UID:'+escape(e.id)+'@jardin-de-dos','DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d+Z$/,'Z'));if(e.time){const start=new Date(`${e.date}T${e.time}:00-04:00`),end=e.endTime?new Date(`${e.date}T${e.endTime}:00-04:00`):new Date(start.getTime()+3600000);const stamp=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d+Z$/,'Z');lines.push('DTSTART:'+stamp(start),'DTEND:'+stamp(end))}else lines.push('DTSTART;VALUE=DATE:'+date,'DTEND;VALUE=DATE:'+addDays(e.date,1).replace(/-/g,''));lines.push('SUMMARY:'+escape(e.title),'DESCRIPTION:'+escape(e.owner+' · '+e.category+'\n'+e.notes),'END:VEVENT')}lines.push('END:VCALENDAR');return lines.map(fold).join('\r\n')+'\r\n'}
