import test from 'node:test';
import assert from 'node:assert/strict';
import {normalize,putTx,deleteTx,deleteAccount,nextPayment,nextWater,energy,buyFlower,accountHealth} from '../app/garden-model.ts';
import {gardenSchema} from '../app/garden-validation.ts';
function setup(){const d=normalize(null);d.accounts=[{id:'a',name:'Cuenta A',owner:'Danelson',balance:1000,budget:100,color:'#648b60'},{id:'b',name:'Cuenta B',owner:'Compartido',balance:200,budget:0,color:'#648b60'}];return d}
const transfer={id:'transfer',type:'transfer',amount:80,account:'a',to:'b',category:'Otros',note:'Transferencia',date:'2026-10-04',person:'Danelson'};
test('editar tipo, monto y cuenta revierte ambos lados antes de aplicar el nuevo movimiento',()=>{let d=putTx(setup(),transfer);assert.deepEqual(d.accounts.map(a=>a.balance),[920,280]);d=putTx(d,{...transfer,type:'expense',account:'b',to:undefined,amount:35});assert.deepEqual(d.accounts.map(a=>a.balance),[1000,165]);assert.equal(d.tx.length,1);d=deleteTx(d,transfer.id);assert.deepEqual(d.accounts.map(a=>a.balance),[1000,200]);});
test('borrar cuenta revierte transferencias en cuentas sobrevivientes y elimina referencias',()=>{let d=putTx(setup(),transfer);d=putTx(d,{...transfer,id:'expense',type:'expense',amount:20,to:undefined});d.rec=[{id:'rec',name:'Pago',account:'a',amount:5,date:'2026-10-04',frequency:'monthly'}];d=deleteAccount(d,'a');assert.equal(d.accounts[0].balance,200);assert.equal(d.tx.length,0);assert.equal(d.rec.length,0);assert(gardenSchema.safeParse(d).success)});
test('transferencia inválida no modifica datos originales',()=>{const d=setup();assert.throws(()=>putTx(d,{...transfer,to:'a'}));assert.equal(d.accounts[0].balance,1000);assert.throws(()=>putTx(d,{...transfer,amount:-20}));});
test('una referencia de destino antigua en un gasto no borra un movimiento ajeno',()=>{const d=setup();d.tx=[{...transfer,type:'expense',to:'b'}];const result=deleteAccount(d,'b');assert.equal(result.tx.length,1);assert.equal(result.accounts[0].balance,1000);assert.equal(normalize(d).tx[0].to,undefined)});
test('fechas mensuales y anuales se ajustan al fin de mes sin desbordarse',()=>{assert.equal(nextPayment('2026-01-31','monthly','2026-01-31'),'2026-02-28');assert.equal(nextPayment('2024-02-29','yearly','2024-02-29'),'2025-02-28');assert.equal(nextPayment('2026-09-20','weekly','2026-10-04'),'2026-10-11')});
test('editar y borrar un riego recalcula calendario; dos riegos el mismo día no duplican energía',()=>{const d=setup();d.realPlants=[{id:'p',name:'Lola',species:'Monstera',owner:'Alana',water:250,interval:7,start:'2026-10-01',notes:'',color:'#648b60',flower:'daisy',logs:[{id:'w1',date:'2026-10-03',amount:250,person:'Alana',note:''},{id:'w2',date:'2026-10-03',amount:40,person:'Alana',note:''}]}];assert.equal(nextWater(d.realPlants[0]),'2026-10-10');assert.equal(energy(d).xp,10);d.realPlants[0].logs[0].date='2026-10-04';assert.equal(nextWater(d.realPlants[0]),'2026-10-11');assert.equal(energy(d).xp,20);d.realPlants[0].logs=[];assert.equal(nextWater(d.realPlants[0]),'2026-10-01');assert.equal(energy(d).xp,0)});
test('comprar flores gasta energía sin tocar balances y editar no genera premios extra',()=>{let d=setup();for(let i=0;i<4;i++)d=putTx(d,{...transfer,id:'t'+i,type:'income',to:undefined,amount:1});const balances=d.accounts.map(a=>a.balance);d=buyFlower(d,'sunflower');assert.equal(energy(d).available,0);assert.equal(energy(d).xp,60);assert.deepEqual(d.accounts.map(a=>a.balance),balances);assert.throws(()=>buyFlower(d,'sunflower'));d=putTx(d,{...d.tx[0],amount:2});assert.equal(energy(d).xp,60)});
test('salud reacciona a presupuesto y pago vencido',()=>{let d=setup();assert.equal(accountHealth(d,d.accounts[0],'2026-10-04'),95);d=putTx(d,{...transfer,type:'expense',to:undefined,amount:150});assert.equal(accountHealth(d,d.accounts[0],'2026-10-04'),60);d.rec=[{id:'r',name:'Pago',account:'a',amount:5,date:'2026-10-03',frequency:'monthly'}];assert.equal(accountHealth(d,d.accounts[0],'2026-10-04'),40)});
test('validación rechaza cantidades negativas, fechas inválidas y referencias borradas',()=>{const d=putTx(setup(),transfer);assert(gardenSchema.safeParse(d).success);d.tx[0].amount=-1;assert(!gardenSchema.safeParse(d).success);d.tx[0].amount=80;d.tx[0].date='2026-02-31';assert(!gardenSchema.safeParse(d).success);d.tx[0].date='2026-10-04';d.accounts=[];assert(!gardenSchema.safeParse(d).success)});
