export type Flower='daisy'|'sunflower'|'orchid'|'cosmic';
export type Account={id:string,name:string,owner:string,balance:number,budget:number,color:string,flower?:Flower,pot?:string};
export type Tx={id:string,type:'expense'|'income'|'transfer',amount:number,account:string,to?:string,category:string,note:string,date:string,person:string,recurringId?:string,recurringPeriod?:string,recurringDue?:string};
export type Rec={id:string,name:string,amount:number,account:string,date:string,frequency:'weekly'|'monthly'|'yearly',anchorDay?:number};
export type Goal={id:string,name:string,target:number,saved:number};
export type Water={id:string,date:string,amount:number,person:string,note:string};
export type RealPlant={id:string,name:string,species:string,owner:string,water:number,interval:number,start:string,notes:string,color:string,flower:Flower,logs:Water[]};
export type AgendaEvent={id:string,title:string,owner:string,date:string,time:string,endTime:string,category:string,notes:string,done:boolean,source?:string,sourceUid?:string};
export type Data={names:string[],accounts:Account[],tx:Tx[],rec:Rec[],goals:Goal[],realPlants:RealPlant[],spent:number,unlocked:Flower[],effects:string[],disabledEffects:string[],events:AgendaEvent[]};
export const fresh:Data={names:['Danelson','Alana'],accounts:[],tx:[],rec:[],goals:[],realPlants:[],spent:0,unlocked:['daisy'],effects:[],disabledEffects:[],events:[]};
export const flowers:{id:Flower,name:string,color:string,cost:number,xp:number,description:string}[]=[{id:'daisy',name:'Margarita',color:'#f5f1d9',cost:0,xp:0,description:'Tu primera flor. Pequeña, luminosa, llena de posibilidades.'},{id:'sunflower',name:'Girasol',color:'#f2bd45',cost:60,xp:60,description:'Pétalos dorados que siguen al sol. Crece alto y florece grande.'},{id:'orchid',name:'Orquídea',color:'#c58cc8',cost:120,xp:150,description:'Flores en cascada y pétalos suaves. Un jardín con personalidad.'},{id:'cosmic',name:'Flor cósmica',color:'#85cbd2',cost:200,xp:300,description:'Pétalos estelares y destellos. Para quienes cultivan universos.'}];
export function normalize(raw:Partial<Data>|null):Data{const d:Data={...structuredClone(fresh),...raw,tx:(raw?.tx||[]).map(t=>({...t,to:t.type==='transfer'?t.to:undefined})),realPlants:raw?.realPlants||[],spent:raw?.spent||0,unlocked:raw?.unlocked||['daisy'],effects:raw?.effects||[],disabledEffects:raw?.disabledEffects||[],events:raw?.events||[]};
if(d.names[1]==='Mi pareja'){d.names=[d.names[0],'Alana'];d.accounts=d.accounts.map(a=>({...a,owner:a.owner==='Mi pareja'?'Alana':a.owner}));d.tx=d.tx.map(t=>({...t,person:t.person==='Mi pareja'?'Alana':t.person}));d.realPlants=d.realPlants.map(p=>({...p,owner:p.owner==='Mi pareja'?'Alana':p.owner,logs:p.logs.map(w=>({...w,person:w.person==='Mi pareja'?'Alana':w.person}))}));d.events=d.events.map(e=>({...e,owner:e.owner==='Mi pareja'?'Alana':e.owner}));}
d.tx=d.tx.map(t=>{const r=!t.recurringId&&t.category==='Recurrentes'?d.rec.find(r=>r.name===t.note&&r.account===t.account):undefined;return r?{...t,recurringId:r.id,recurringPeriod:periodKey(r.frequency,t.date),recurringDue:t.date}:t});return d}

export const money=(n:number)=>new Intl.NumberFormat('es-PR',{style:'currency',currency:'USD'}).format(n);
export function today(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/Puerto_Rico',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return `${p.find(x=>x.type==='year')!.value}-${p.find(x=>x.type==='month')!.value}-${p.find(x=>x.type==='day')!.value}`}
export function addDays(date:string,days:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
export function nextWater(p:RealPlant){const last=p.logs.map(l=>l.date).sort().at(-1);return last?addDays(last,p.interval):p.start}
export function daysBetween(a:string,b:string){return Math.round((Date.parse(b+'T12:00:00Z')-Date.parse(a+'T12:00:00Z'))/86400000)}
export function energy(data:Data){const waters=data.realPlants.reduce((s,p)=>s+new Set(p.logs.map(l=>l.date)).size,0);const xp=data.tx.length*15+data.goals.filter(g=>g.saved>=g.target).length*100+waters*10;return {xp,available:Math.max(0,xp-data.spent),level:Math.floor(xp/150)+1}}
const round=(v:number)=>Math.round((v+Number.EPSILON)*100)/100;
export function applyTx(data:Data,t:Tx,direction=1){const a=data.accounts.find(a=>a.id===t.account);if(!a)throw Error('La cuenta de origen ya no existe.');if(!Number.isFinite(t.amount)||t.amount<=0)throw Error('El monto debe ser mayor de cero.');if(t.type==='transfer'){const b=data.accounts.find(a=>a.id===t.to);if(!b||b.id===a.id)throw Error('Escoge una cuenta de destino diferente.');b.balance=round(b.balance+t.amount*direction)}a.balance=round(a.balance+(t.type==='income'?1:-1)*t.amount*direction)}
export function putTx(data:Data,t:Tx){const next=structuredClone(data),old=next.tx.find(x=>x.id===t.id);if(old){applyTx(next,old,-1);t={...t,recurringId:old.recurringId,recurringPeriod:old.recurringPeriod,recurringDue:old.recurringDue};if(old.recurringId&&t.type!=='expense')throw Error('Un pago recurrente debe seguir siendo un gasto.');}applyTx(next,t);next.tx=old?next.tx.map(x=>x.id===t.id?t:x):[t,...next.tx];return next}
export function deleteTx(data:Data,id:string){const next=structuredClone(data),t=next.tx.find(x=>x.id===id);if(t){applyTx(next,t,-1);if(t.recurringId){const r=next.rec.find(r=>r.id===t.recurringId);if(r&&!next.tx.some(x=>x.id!==id&&x.recurringId===t.recurringId&&x.date>t.date))r.date=t.recurringDue||t.date;}}next.tx=next.tx.filter(x=>x.id!==id);return next}
export function deleteAccount(data:Data,id:string){const next=structuredClone(data);const affected=next.tx.filter(t=>t.account===id||(t.type==='transfer'&&t.to===id));for(const t of affected)applyTx(next,t,-1);next.tx=next.tx.filter(t=>t.account!==id&&(t.type!=='transfer'||t.to!==id));next.rec=next.rec.filter(r=>r.account!==id);next.accounts=next.accounts.filter(a=>a.id!==id);return next}
export function nextPayment(date:string,frequency:Rec['frequency'],after:string){let d=new Date(date+'T12:00:00Z');const day=d.getUTCDate();let guard=0;do{if(frequency==='weekly')d.setUTCDate(d.getUTCDate()+7);else{d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+(frequency==='yearly'?12:1));d.setUTCDate(Math.min(day,new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate()))}if(++guard>20000)throw Error('Revisa la fecha del pago.')}while(d.toISOString().slice(0,10)<=after);return d.toISOString().slice(0,10)}
export function accountHealth(data:Data,a:Account,date=today()){const used=data.tx.filter(t=>t.account===a.id&&t.type==='expense'&&t.date.startsWith(date.slice(0,7))).reduce((s,t)=>s+t.amount,0);const overdue=data.rec.some(r=>r.account===a.id&&r.date<date&&!paidInPeriod(data,r,date));return Math.max(15,Math.min(100,85+(a.balance>0?10:-35)-(a.budget>0&&used>a.budget?35:0)-(overdue?20:0)))}
export function buyFlower(data:Data,id:Flower){const f=flowers.find(f=>f.id===id)!;if(data.unlocked.includes(id))throw Error('Esta flor ya está desbloqueada.');const e=energy(data);if(e.xp<f.xp||e.available<f.cost)throw Error('Todavía necesitas más energía para esta flor.');return {...data,unlocked:[...data.unlocked,id],spent:data.spent+f.cost}}

export function periodKey(frequency:Rec['frequency'],date:string){if(frequency==='monthly')return date.slice(0,7);if(frequency==='yearly')return date.slice(0,4);const d=new Date(date+'T12:00:00Z'),day=d.getUTCDay();d.setUTCDate(d.getUTCDate()-((day+6)%7));return d.toISOString().slice(0,10)}
export function paidInPeriod(data:Data,r:Rec,date=today()){return data.tx.some(t=>(t.recurringId===r.id||!t.recurringId&&t.category==='Recurrentes'&&t.note===r.name&&t.account===r.account)&&(t.recurringPeriod===periodKey(r.frequency,date)||periodKey(r.frequency,t.date)===periodKey(r.frequency,date)))}
export function recurrenceStatus(data:Data,r:Rec,date=today()){if(paidInPeriod(data,r,date))return {allowed:false,label:'Pagado este periodo'};if(r.date>date)return {allowed:false,label:'Disponible el '+r.date};return {allowed:true,label:'Registrar pago'}}
export function payRecurring(data:Data,id:string,person:string,date=today(),txId=crypto.randomUUID()){const r=data.rec.find(r=>r.id===id);if(!r)throw Error('El recurrente ya no existe.');const status=recurrenceStatus(data,r,date);if(!status.allowed)throw Error(status.label);let next=putTx(data,{id:txId,type:'expense',amount:r.amount,account:r.account,category:'Recurrentes',note:r.name,date,person,recurringId:r.id,recurringPeriod:periodKey(r.frequency,date),recurringDue:r.date});const anchor=r.anchorDay||Number(r.date.slice(-2));let due=r.date,count=0;do{due=advanceRecurrence(due,r.frequency,anchor);if(++count>20000)throw Error('Revisa la fecha del recurrente.')}while(due<=date||periodKey(r.frequency,due)===periodKey(r.frequency,date));next.rec=next.rec.map(x=>x.id===id?{...x,date:due,anchorDay:anchor}:x);return next}

export function advanceRecurrence(date:string,frequency:Rec['frequency'],day=Number(date.slice(-2))){if(frequency==='weekly')return addDays(date,7);const d=new Date(date+'T12:00:00Z');d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+(frequency==='yearly'?12:1));d.setUTCDate(Math.min(day,new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate()));return d.toISOString().slice(0,10)}
